- name: Apache | Don't Listen on All Interfaces
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    state: absent 

- name: Apache | Listen Single IPv4 Interface
  lineinfile: 
    path: /etc/apache2/ports.conf
    insertafter: '#Listen'
    line: 'Listen {{ ansible_default_ipv4.address }}:80'

- name: Apache | Start Services 
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: 
    - apache2

- name:  Apache | Make Symlink Apache Web Root 
  file: 
    src: "{{ redmine_path }}/public"
    dest: /var/www/html/redmine
    state: link

- name:  Apache | Grant Permissions Web Directory
  file:
    path: /var/www/html/redmine
    owner: www-data
    group: www-data
    mode: u+rwxs,g+rwxs,o+rx

- name:  Apache | Copy Passenger Config File
  become: yes
  become_user: root
  copy:
    src: templates/passenger.conf.j2
    dest: /etc/apache2/mods-available/passenger.conf 

- name:  Apache | Copy Redmine Config File
  become: yes
  become_user: root 
  copy:
    src: templates/redmine.conf.j2
    dest: /etc/apache2/sites-available/redmine.conf

- name:  Apache | Copy Default  File
  become: yes
  become_user: root
  copy:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf.j2


- name: Redmine Setup | Passenger Services Module
  become: yes
  shell: 'a2enmod passenger'
  args:
    executable: /bin/bash

- name: Redmine Setup | Passenger Services Module
  become: yes
  shell: 'apache2ctl restart'
  args:
    executable: /bin/bash