- name: Don't Listen on All Interfaces
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen 80'
    state: absent 

- name: Listen Single IPv4 Interface
  lineinfile: 
    path: /etc/apache2/ports.conf
    insertafter: '#Listen'
    line: 'Listen {{ ansible_default_ipv4.address }}:80'

- name: Start Services 
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: 
    - apache2

