- name: Source .bashrc
  become: yes
  shell: ". ~/.bashrc" 
  args: 
    executable: /bin/bash

- name: Redmine Setup | Gem Update for System 
  shell: "~/.rbenv/shims/gem update --system"
  args: 
    chdir: "{{ redmine_path }}" 
    executable: /bin/bash

- name: Run Redmine | Set Local Path
  shell: '~/.rbenv/shims/bundle config set 
         --local path vendor/bundle'
  args:
    chdir: "{{ redmine_path }}"
    executable: /bin/bash

- name: Redmine Setup | Bundle Install 
  shell: "~/.rbenv/shims/bundle install"
  args: 
    chdir: "{{ redmine_path }}" 
    executable: /bin/bash

- name: Redmine Setup | Bundle Update 
  shell: "~/.rbenv/shims/bundle update"
  args: 
    chdir: "{{ redmine_path }}" 
    executable: /bin/bash

- name: Redmine Setup | Install Strscan
  gem: 
    name: strscan
    state: latest
    executable: "~/.rbenv/shims/gem"

- name: Redmine Setup | Install Io-Wait
  gem: 
    name: io-wait
    state: latest
    executable: "~/.rbenv/shims/gem"

- name: Redmine Setup | Create Gemfile.lock
  file: 
    path: "{{ redmine_path }}/Gemfile.lock"
    state: touch

- name: Run Redmine | Generate Secret 
  shell: '~/.rbenv/shims/bundle exec 
          rake generate_secret_token'
  args:
    chdir: "{{ redmine_path }}"
    executable: /bin/bash

- name: Run Redmine | Rake DB Migrate
  shell: 'RAILS_ENV=production ~/.rbenv/shims/bundle 
          exec rake db:migrate'
  args:
    chdir: "{{ redmine_path }}"
    executable: /bin/bash

- name: Run Redmine | Rake Load Defaults
  expect:
    command: /bin/bash -c "~/.rbenv/shims/bundle exec rake redmine:load_default_data RAILS_ENV=production"
    responses:
      (.*)Select language(.*): en
  args:
    chdir: "{{ redmine_path }}"
  register: load_defaults
  ignore_errors: yes

- debug:
    var: load_defaults

- name: Run Redmine | Make Tmp/Pdf
  file:
    path: "{{ redmine_path }}/tmp/pdf"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ group_name }}"
    mode: 0755

- name: Run Redmine | Open Port 3000
  become: yes
  become_user: root
  shell: 'sudo ufw allow 3000/tcp'
  args:
    chdir: "{{ redmine_path }}"
    executable: /bin/bash

- name: Run Redmine | Rake Run Test Server
  shell: ' ~/.rbenv/shims/bundle exec rails server -u webrick -e production -d'
  args:
    chdir: "{{ redmine_path }}"
    executable: /bin/bash


