- name: Create Group 
  group:
    name: "{{ group_name }}"

- name: Create User
  user:
    name: "{{ user_name }}"
    create_home: true
    groups: "{{ group_name }}, admin"
    comment: 'Redmine Management Account'
    expires: -1
    state: present 
    shell: /bin/bash
    password:  "{{ user_password | password_hash('sha512') }}"
    update_password: on_create

- name: Install SSH Key
  authorized_key:
    user: "{{ user_name }}"
    state: present
    manage_dir: true 
    key: "{{ lookup('file', '/Users/intimaria/.ssh/id_rsa.pub') }}"

- name: Set-up Redmine Sudo Access 
  copy:
    dest: /etc/sudoers.d/redmine
    content: "redmine ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"