- name: User | Create Group
  become: yes
  group:
    name: "{{ group_name }}"

- name: User | Create User
  user:
    name: "{{ user_name }}"
    create_home: yes
    groups: 
      - "{{ group_name }}"
    comment: 'Redmine Management Account'
    expires: -1
    state: present
    shell: /bin/bash
    password:  "{{ user_password | password_hash('sha512', 'AZ') }}"
    update_password: on_create
    generate_ssh_key: yes

- name: User | Set-up Redmine Sudo Access 
  copy:
    dest: /etc/sudoers.d/redmine
    content: "redmine ALL=(ALL) NOPASSWD:ALL"
    validate: "/usr/sbin/visudo -cf %s"
