- name: Create Group 
  group:
    name: "{{ group_name }}"

- name: Create User
  user:
    name: "{{ user_name }}"
    create_home: true
    groups: "{{ group_name }}"
    comment: 'Redmine Management Account'
    expires: -1
    state: present 
    shell: /bin/bash
    password:  "{{ user_password | password_hash('sha512') }}"
    update_password: on_create