- name: Check If Redmine Already Downloaded
  stat: 
    path: "{{ redmine_path }}"
  register: downloaded 
  ignore_errors: yes
  tags: 
    - install_redmine

- name: Download Resource and Untar File 
  become: yes
  become_user: root
  unarchive:
    src: "https://redmine.org/releases/redmine-{{ redmine.version }}.tar.gz"
    dest: "/srv"
    remote_src: yes
  when: not downloaded.stat.exists
  tags: 
    - install_redmine

- name: Give ownership of redmine to redmine
  become: yes
  become_user: root
  file: 
    path: "{{ redmine_path }}"
    owner: "{{ group_name }}"
    group: "{{ group_name }}"
    mode: u+rwxs,g+rwxs,o+rx
    recurse : yes
    state: directory

- name: Delete Tarfile
  file:
    state: absent
    path: "{{ redmine_path }}-{{ redmine.version }}.tar.gz"
  tags: 
    - install_redmine

- name: Make Symlink to Redmine 
  become: yes
  become_user: root
  file:
    src: "{{ redmine_path }}-{{ redmine.version }}"
    dest: "{{ redmine_path }}"
    # owner: "{{ group_name }}"
    # group: "{{ group_name }}"
    # mode: u+rwxs,g+rwxs,o+rx
    state: link
  tags: 
    - install_redmine

- name: Copy DB Config File
  copy:
    src: templates/database.yml.j2
    dest: "{{ redmine_path }}/config/database.yml"
  tags: 
    - install_redmine