- name: Download Redmine | Check If Redmine Already Downloaded
  stat: 
    path: "{{ redmine_path }}"
  register: downloaded 
  ignore_errors: yes

- name: Download Redmine | Download Resource and Untar File 
  become: yes
  become_user: root
  unarchive:
    src: "https://redmine.org/releases/redmine-{{ redmine.version }}.tar.gz"
    dest: "/srv"
    remote_src: yes
    owner: "{{ group_name }}"
    group: "{{ group_name }}"
    mode: u+rwxs,g+rwxs,o+rx
  when: not downloaded.stat.exists

- name: Download Redmine |Delete Tarfile
  file:
    state: absent
    path: "{{ redmine_path }}-{{ redmine.version }}.tar.gz"
  
- name: Download Redmine | Make Symlink to Redmine 
  become: yes
  become_user: root
  file:
    src: "{{ redmine_path }}-{{ redmine.version }}"
    dest: "{{ redmine_path }}"
    state: link

- name: Download Redmine | Copy DB Config File
  copy:
    src: templates/database.yml.j2
    dest: "{{ redmine_path }}/config/database.yml"

