- name: Redmine Setup  | Check Installed Ruby 
  shell: "~/.rbenv/bin/rbenv versions | grep {{ rbenv.default_ruby }}"
  register: ruby_installed
  ignore_errors: yes

- name: Redmine Setup | Install Ruby
  shell: "~/.rbenv/bin/rbenv install {{ rbenv.default_ruby }} -k"
  when: "ruby_installed.rc == 1"

- name: Redmine Setup | Local Ruby Version
  shell: "~/.rbenv/bin/rbenv global {{ rbenv.default_ruby }}"
  args: 
    chdir: "{{ redmine_path }}"
  ignore_errors: yes

- name: Redmine Setup | Install Bundler 
  become: yes
  become_user: root                                                                                                                                                                                                              
  shell: gem install bundler                                                                                                                                              
  args: 
    chdir: "{{ redmine_path }}" 
    executable: /bin/bash

- name: Redmine Setup | Install Passenger
  gem: 
    name: passenger
    state: latest
    user_install: no
    executable: "~/.rbenv/shims/gem"




