- name: Redmine Setup  | Check Installed Ruby 
  shell: "~/.rbenv/bin/rbenv versions | grep {{ rbenv.default_ruby }}"
  register: ruby_installed
  ignore_errors: yes

- name: Redmine Setup | Install Ruby
  shell: "~/.rbenv/bin/rbenv install {{ rbenv.default_ruby }} -k"
  when: "ruby_installed.rc == 1"

- name: Redmine Setup | Local Ruby Version
  shell: "~/.rbenv/bin/rbenv local {{ rbenv.default_ruby }}"
  args: 
    chdir: "{{ redmine_path }}"
  ignore_errors: yes

- name: Redmine Setup | Install Bundler                                                                                                                                                                                                               
  gem:                                                                                                                                              
    name: bundler

- name: Redmine Setup | Install Passenger
  gem: 
    name: passenger
    state: latest
    user_install: no

- name: Redmine Setup | Create Gemfile.lock
  file: 
    path: "{{ redmine_path }}/Gemfile.lock"
    state: touch

- name: Redmine Setup | Bundle Install 
  shell: "~/.rbenv/shims/bundle install"
  args: 
    chdir: "{{ redmine_path }}" 
    executable: /bin/bash

