# - name: insert nginx conf file 

- name: Make sure www-data part of www-data group
  become: yes
  user:
    name: www-data
    groups: www-data 
    append: yes
  
- name: Make Symlink to Redmine Public
  become: yes
  file:
    src: "{{ redmine_path }}/public"
    dest: /var/www/html/redmine
    state: link

- name: Chown folder contents to www-data group
  become: yes
  file: 
    path: /var/www/html/redmine/
    owner: www-data
    group: www-data
    recurse : yes
    state: directory
    mode: 0755

- name: Copy Nginx Config File
  become: yes
  become_user: root
  copy:
    src: templates/redmine.conf.j2
    dest: "/etc/nginx/sites-available/redmine.conf"

- name: Make Symlink to sites enabled 
  become: yes
  file:
    src: /etc/nginx/sites-available/redmine.conf
    dest: /etc/nginx/sites-enabled/redmine.conf
    state: link

- name: Remove Default Link
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx service
  become: yes
  service: 
    name: mysql
    daemon_reload: yes
    state: restarted
    enabled: yes