---
- name: Setup System
  hosts: all
  become: yes
  become_user: root
  roles: 
    - system # APT update && upgrade -y
    - user # Create a Redmine User
    - db # Create a mySql database & user 

- name: Install Redmine
  hosts: all
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo
  roles: 
    - rbenv # Install rbenv
    - install_redmine # Download Redmine & Copy DB config
    - ruby # Install Ruby & Bundler 
    - run_redmine # Run Bundler, Install Gems, Rake DB, Server Up