---
- name: Setup System
  hosts: all
  become: true
  roles: 
    - system
    - user
    - db
    - download_redmine
    - apache

- name: Install Redmine
  hosts: all
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo
  roles: 
    - ruby
    - install