---
- name: Setup System
  hosts: all
  become: yes
  become_user: root
  roles: 
    - system # APT update && upgrade -y
    - user # Create a Redmine User

- name: Create Database
  hosts: all
  roles: 
    - db # Create a mySql database & user 

- name: Install Redmine
  hosts: all
  become: yes
  become_user: "{{ user_name }}"
  roles: 
    - rbenv # Install rbenv
    - install_redmine # Download Redmine & Copy DB config
    - ruby # Install Ruby & Bundler 
    - run_redmine # Run Bundler, Install Gems, Rake DB, Server Up

- name: Nginx
  hosts: all 
  # tasks:
  # - name: "Check if Ngninx is installed"
  #   package_facts:
  #     manager: "auto"
  # - include_role:
  #     name: install_nginx # Install nginx
  #   when: "'nginx' not in ansible_facts.packages"
  roles: 
    - install_nginx
    - run_nginx # Configure & run reverse proxy service
