---
- name: Setup System
  hosts: all
  become: yes
  become_user: root
  roles: 
    - system # APT update && upgrade -y
    - user # Create a Redmine User
    - db # Create a mySql database & user 

- name: Install Redmine
  hosts: all
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo
  roles: 
    - ruby # Install rbenv & ruby
    - download_redmine # Download & extract Redmine
    - setup_redmine # Install Gems & Passenger Service 

- name: Setup Apache
  hosts: all
  become: yes
  become_user: root
  roles:
    - apache # Copy configuration & restart service 

- name: Run Redmine
  hosts: all
  become: yes
  become_user: "{{ user_name }}"
  become_method: sudo
  roles: 
    - run_redmine # Bundler & Gems 