- name: Apt install Rbenv Dependencies 
  register: updatesys
  apt:
    name: 
      - git
      - curl
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
      - autoconf
      - bison
      - build-essential
      - libyaml-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm-dev
      - libreadline6-dev 
      - zlib1g-dev 

- name: Download Rbenv
  become: yes
  become_user: redmine
  become_method: sudo
  git: 
    repo: https://github.com/sstephenson/rbenv.git
    dest: "/home/{{ user_name }}/.rbenv"
    version: v1.2.0

- name: Download Ruby-Build
  become: yes
  become_user: redmine
  become_method: sudo
  git: 
    repo: https://github.com/rbenv/ruby-build.git
    dest: "/home/{{ user_name }}/.rbenv/plugins/ruby-build"

- name: Export Rbenv to PATH
  become: yes
  become_user: redmine
  become_method: sudo
  lineinfile: 
    dest: "/home/{{ user_name}}/.bashrc" 
    line: "export PATH=\"$HOME/.rbenv/bin:$PATH\""

- name: Edit .bashrc
  become: yes
  become_user: redmine
  become_method: sudo
  lineinfile: 
    dest: "/home/{{ user_name}}/.bashrc"
    line: "eval \"$(rbenv init -)\""


- name: Install Ruby
  become: yes
  become_user: redmine
  become_method: sudo
  shell: "/home/{{ user_name }}/.rbenv/bin/rbenv install {{ rbenv.default_ruby }} -k"
  ignore_errors: yes